// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwhgurkljicybwektics.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3aGd1cmtsamljeWJ3ZWt0aWNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDg5OTEsImV4cCI6MjA2MTMyNDk5MX0.uroNg2gQyj3HRpzbyAaAfgDEjOp2MmeHANIt509bPtQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);